-- Execute this script in the Supabase SQL Editor

CREATE TABLE public.heatmap_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    timestamp TEXT,
    data JSONB
);

CREATE TABLE public.summary_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    timestamp TEXT,
    data JSONB,
    alerts JSONB
);

-- Note: We are allowing all for RLS for simplicity since we secure the routes on our API.
-- In production, make sure not to expose your Anon Key if you enable full access.
